config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                   path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  root "products#index"
  get 'products/index_moderator', to: 'products#index_moderator', as: 'index_moderator'

  resources :products
  resources :chats
  resources :orders
  resources :reviews
  resources :messages
  resources :users

end

app/models/chat.rb
class Chat < ApplicationRecord
  validates :id_user, presence: true
  validates :moderator_id, presence: true
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chat = Chat.all
  end

  def new
    @users = User.all
    @chat = Chat.new
  end

  def show
    @chat = Chat.find(params[:id])
    all_messages = Message.all
    messages_chat = Array.new
    all_messages.each do |message|
      if message.id_chat == @chat.id
        messages_chat.push(message)
      end
    end
    @messages = messages_chat
  end

  def create
    all_chats = Chat.all
    is_any = false
    all_chats.each do |chat|
      if chat.id_user == chat_params[:id_user].to_i && chat.moderator_id == chat_params[:moderator_id].to_i
        is_any = true
      end
    end
    if is_any == false
      @chat = Chat.new(chat_params)
      if @chat.save
        redirect_to @chat
      else
        render @chat.errors, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @chat = Chat.find(params[:id])
    @messages = Message.all

    @messages.each do |message|
      if message.id_chat == @chat.id
        message.destroy
      end
    end

    if @chat.destroy
      redirect_to chats_path
    else
      render json: @chat.errors, status: :unprocessable_entity
    end
  end

  def chat_params
    params.require(:chat).permit(:moderator_id, :id_user)
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_form.html.erb
<%= form_with(model: @chat, url: chats_path, local: true) do |form| %>
  <%= form.hidden_field :id_user, value: current_user.id %>
  <div class="field is-grouped">
    <div class="control is-expanded">
      <div class="select is-rounded">
        <%= form.select :moderator_id, options_for_select(@users.select { |user| user.moderator? || user.admin? }.map { |user| [user.name, user.id] }) %>
      </div>
    </div>
    <div class="control">
      <%= form.submit "Crear Chat", class: "button is-primary is-rounded" %>
    </div>
  </div>
<% end %>

app/views/chats/_index_admin.html.erb
<div id="chats">
    <div class="content is-center has-text-centered is-size-3">
        <h1>Chats</h1>
    </div>
    <div class="columns is-centered">
        <div class="column is-one-third">
            <% @chat.each do |chat| %>
                <% if (current_user.moderator? && chat.moderator_id == current_user.id) || current_user.admin?%>
                    <% user = User.find(chat.id_user)%>
                    <div class="field is-grouped">
                        <div class="control is-expanded">
                            <button class="button is-medium" onclick="window.location.href='<%= chat_path(chat) %>'">
                                <%= user.name %>
                            </button>
                        </div>
                        <div class="control">
                            <%= button_to "Delete chat", chat_path(chat.id), method: :delete, class: "button is-danger is-rounded"%>
                        </div>
                    </div>
                <%end%>
            <% end %>
        </div>
    </div>
</div>

app/views/chats/_index_user.html.erb
<div class="content is-center has-text-centered is-size-3">
  <h1>Chats</h1>
</div>
<div class="columns is-centered">
  <div class="column is-one-third">
    <% @chat.each do |chat| %>
      <% if chat.id_user == current_user.id %>
        <div class="has-text-centered">
          <button class="button is-medium" onclick="window.location.href='<%= chat_path(chat) %>'">
            <%moderador = User.find(chat.moderator_id)%>
            <%= moderador.name %>
          </button>
        </div>
      <% end %>
    <% end %>
    <div class="has-text-centered">
      <%= link_to "New Chat", new_chat_path, class: "button is-primary is-rounded" %>
    </div>
  </div>
</div>

app/views/chats/index.html.erb
<% if user_signed_in? %>

  <p style="color: green"><%= notice %></p>

  <% if current_user.admin? || current_user.moderator?%>
    <%= render "index_admin" %>

  </div>

  <% elsif current_user.user? %>
    <%= render "index_user" %>

  <% end %>

<% else %>
  <meta http-equiv="refresh" content="0; url=/">

<% end %>

app/views/chats/new.html.erb
<%if user_signed_in?%>
  <div class="content is-center has-text-centered is-size-3">
    <h1>Creando un Chat</h1>
  </div>
  <div class="content is-center has-text-centered is-size-6">
    <h1>Seleccione un Moderador al cual contactar</h1>
  </div>
  <div class="columns is-centered">
    <div class="column is-one-third">
      <%= render "form", chat: @chat%>
    </div>
  </div>
<%else%>
  <meta http-equiv="refresh" content="0; url=/">

<% end %>

app/views/chats/show.html.erb
<% if user_signed_in? %>

  <p style="color: green"><%= notice %></p>
  <% if current_user.id == @chat.id_user || current_user.admin? || current_user.id == @chat.moderator_id %>
    <div class="content is-center has-text-centered is-size-6">
      <h1>Chat</h1>
    </div>
    <div id="chat" class="box" style="height: 500px; overflow-y: auto;">
      <% @messages.each do |message| %>
        <%usuario = User.find(message.id_user)%>
        <%if usuario.admin? || usuario.moderator?%>
          <article class="message is-danger is-medium">
            <div class="message-body">
              <%= message.content %>
            </div>
          </article>
        <% else %>
          <article class="message is-medium">
            <div class="message-body">
              <%= message.content %>
            </div>
          </article>
        <% end %>
      <% end %>
    </div>
    <%if current_user.admin? == false%>
      <form action="/messages" method="post" style="display: flex; align-items: center;">
        <div style="flex: 1;">
          <input type="hidden" name="message[name]" value="<%= current_user.name %>: ">
          <input class="input is-rounded" type="text" placeholder="Escriba su mensaje" name="message[content]">
          <input type="hidden" name="message[id_chat]" value="<%= @chat.id %>">
          <input type="hidden" name="message[id_user]" value="<%= current_user.id %>">
        </div>
        <div>
          <button class="button is-link" type="submit">Enviar</button>
        </div>
      </form>
    <%end%>
  <%end%>

<% else %>
    <meta http-equiv="refresh" content="0; url=/">

<% end %>