config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                   path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  root "products#index"
  get 'products/index_moderator', to: 'products#index_moderator', as: 'index_moderator'

  resources :products
  resources :chats
  resources :orders
  resources :reviews
  resources :messages
  resources :users

end

app/models/product.rb
class Product < ApplicationRecord
	has_one_attached :image
  has_many :review, dependent: :destroy
  has_one :order
  has_one :user, through: :order
  validates :name, presence: true
  validates :price, presence: true
  validates :image, presence: true
  validates :id_user, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def index_moderator
		@products = Product.all
  end

	def show
		@product = Product.find(params[:id])
	end

	def edit
		@product = Product.find(params[:id])
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to products_url
		else
			flash.now[:error] = @product.errors.full_messages.join(", ")
    		render :new, status: :unprocessable_entity
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])

		if @product.update(product_params)
			redirect_to product_url(@product), notice: "Product was successfully updated."
		else
			flash.now[:error] = @product.errors.full_messages.join(", ")
    		render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.delete
		redirect_to products_url, notice: "Product was successfully destroyed."
	end

	def product_params
		params.require(:product).permit(:name, :price, :image, :id_user)
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="box mx-6 mr-6 is-align-self-center">

	<%= form_with(model: @product) do |form| %>

		<div class="field">
			<%= form.label :nombre, class: "label" %>
			<%= form.text_field :name, class: "input", placeholder: "Ingresa el Nombre", value: "" %>

			<% if @product.errors[:name].any? %>
				<p class="help is-danger"> No puede ser vacío </p>
			<% end %>

		</div>

		<div class="field">
			<%= form.label :precio, class: "label" %>
			<%= form.number_field :price, class: "input", placeholder: "Ingresa un Precio", min: 0, value: "" %>

			<% if @product.errors[:price].any? %>
				<p class="help is-danger"> No puede ser vacío </p>
			<% end %>

		</div>

		<div class="file has-name">
			<label class="file-label">
				<%= form.file_field :image, class: "file-input" %>
				<span class="file-cta">
					<span class="file-icon">
						<i class="fas fa-upload"></i>
					</span>

					<span class="file-label">
						Foto del Producto
					</span>
				</span>
			</label>
		</div>

		<br>

		<% if @product.name.present? %>

			<%= form.submit "Actualizar", class:"button is-primary" %>

		<% else %>
			<%= form.hidden_field :id_user, value: current_user.id %>
			<%= form.submit "Agregar", class:"button is-primary" %>

		<% end %>

	<% end %>

</div>

app/views/products/edit.html.erb
<% if user_signed_in? %>

	<%if current_user.admin?%>

		<div class="content is-center has-text-centered is-size-5 mt-5">
			<h2>Editar Producto</h2>
		</div>

		<div class="is-flex is-justify-content-center mt-5">
			<div class="buttons">

				<%= link_to products_path, class: "button is-outlined" do %>
					<span class="icon is-small">
						<i class="fas fa-arrow-left"></i>
					</span>

					<span>
						<p> Volver a Productos </p>
					</span>

				<% end %>

				<%= link_to @product, class: "button is-outlined" do %>
					<span class="icon is-small">
						<i class="fas fa-eye"></i>
					</span>
				<% end %>

			</div>
		</div>

		<%= render "form", product: @product %>

	<% end %>

<% else %>
  	<div class="box mx-6 my-6 is-align-self-center">
		<p> No has iniciado sesión <p>
	</div>

<% end %>

app/views/products/index.html.erb
<div class="content is-center has-text-centered is-size-5 mt-5">
	<h2>Productos</h2>
</div>

<% if user_signed_in? %>

	<% if current_user.admin? || current_user.moderator? %>

		<div class="content is-center has-text-centered mt-5">
			<span class="icon is-small">
				<%= link_to new_product_path, class: "button is-rounded is-primary" do %>
					<i class="fas fa-plus"></i>
				<% end %>
			</span>
		</div>

	<% end %>
<% end %>

<div class="box mx-6 my-5 is-align-self-center">
	<div class="table-container is-flex is-justify-content-center">
		<table class="table is-fullwidth is-centered">

			<thead>
				<tr>
				<th>Imagen</th>
				<th>Producto</th>
				<th>Precio</th>
				<th></th>
				</tr>
			</thead>

			<tbody>

				<% @products.each do |product| %>
					<tr>
						<td>

							<% if product.image.attached? %>

								<figure class="image is-96x96">
									<%= image_tag product.image, class:"is-96x96 has-background-white" %>
								</figure>

							<% else %>

								<figure class="image is-96x96">
									<i class="fa-thin fa-image"></i>
								</figure>

							<% end %>

						</td>

						<td><%= product.name %></td>
						<td><%= product.price %></td>
						<td>
							<%= link_to product, class: "button is-white" do %>
								<span class="icon is-small">
									<i class="fas fa-eye"></i>
								</span>
							<% end %>

						</td>

						<i class="fa-sharp fa-light fa-eye"></i>

					</tr>
				<% end %>

			</tbody>
		</table>
</div>

app/views/products/index_moderator.html.erb

<%="funciono"%>
<div class="content is-center has-text-centered is-size-5 mt-5">
	<h2>Productos</h2>
</div>

<% if user_signed_in? %>

	<% if current_user.admin? || current_user.moderator? %>

		<div class="content is-center has-text-centered mt-5">
			<span class="icon is-small">
				<%= link_to new_product_path, class: "button is-rounded is-primary" do %>
					<i class="fas fa-plus"></i>
				<% end %>
			</span>
		</div>

	<% end %>
<% end %>

<div class="box mx-6 my-5 is-align-self-center">
	<div class="table-container is-flex is-justify-content-center">
		<table class="table is-fullwidth is-centered">

			<thead>
				<tr>
				<th>Imagen</th>
				<th>Producto</th>
				<th>Precio</th>
				<th></th>
				</tr>
			</thead>

			<tbody>

				<% @products.each do |product| %>
                    <%if product.id_user == current_user.id %>
                        <tr>
                            <td>

                                <% if product.image.attached? %>

                                    <figure class="image is-96x96">
                                        <%= image_tag product.image, class:"is-96x96 has-background-white" %>
                                    </figure>

                                <% else %>

                                    <figure class="image is-96x96">
                                        <i class="fa-thin fa-image"></i>
                                    </figure>

                                <% end %>

                            </td>

                            <td><%= product.name %></td>
                            <td><%= product.price %></td>
                            <td>
                                <%= link_to product, class: "button is-white" do %>
                                    <span class="icon is-small">
                                        <i class="fas fa-eye"></i>
                                    </span>
                                <% end %>

                            </td>

                            <i class="fa-sharp fa-light fa-eye"></i>

                        </tr>
                    <%end %>
				<% end %>

			</tbody>
		</table>
</div>

app/views/products/new.html.erb
<% if user_signed_in? %>

  <%if current_user.admin? || current_user.moderator?%>

    <div class="content is-center has-text-centered is-size-5 mt-5">
			<h1> Nuevo Producto </h1>
		</div>

    <%= render "form", product: @product %>

  <% end %>

<% else %>
  <p> No has inciado sesión </p>

<% end %>

app/views/products/show.html.erb
<% if user_signed_in? %>

	<p style="color: green"><%= notice %></p>

	<% if current_user.admin? || current_user.moderator? %>
		<div class="is-flex is-justify-content-center mt-5">
			<div class="buttons">

				<%= link_to edit_product_path(@product), class: "button is-rounded is-primary" do %>
					<span class="icon is-small">
						<i class="fas fa-edit"></i>
					</span>
				<% end %>

				<%= button_to @product, method: :delete, class: "button is-rounded is-danger" do %>
					<span class="icon is-small">
						<i class="fas fa-trash" style="color: #ffffff;"></i>
					</span>
				<% end %>

			</div>
		</div>

	<% end %>

	<div class="box mx-6 my-5 is-align-self-center">
		<div class="table-container is-flex is-justify-content-center">
			<table class="table is-fullwidth">

				<tr>
					<td><b>Imagen:</b></td>
					<td>
						<% if @product.image.attached? %>

							<figure class="image is-96x96">
								<%= image_tag @product.image, class:"is-96x96 has-background-white" %>
							</figure>

						<% else %>

							<figure class="image is-96x96">
								<i class="fa-thin fa-image"></i>
							</figure>

						<% end %>
					</td>
				<tr>
				<tr>
					<td><b>Producto:</b></td>
					<td><i><%= @product.name %></i></td>
				<tr>
				<tr>
					<td><b>Precio:</b></td>
					<td><i><%= @product.price %></i></td>
				<tr>

			</table>
		</div>
	<div>

		<% if current_user.user? %>

			<div class="is-flex is-justify-content-center mt-5">
				<div class="buttons">

					<%= button_to "Solicitar Producto", orders_path(order: { id_product: @product.id, id_user: current_user.id,
							order_date: Date.today.strftime("%d/%m/%Y"), status: "pending" }), method: :post,
							class: "button is-rounded is-primary" %>

				</div>
			</div>

		<% end %>

	</div>

<% else %>
  	<div class="box mx-6 my-6 is-align-self-center">
		<p> No has iniciado sesión <p>
	</div>

<% end %>