config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                   path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  root "products#index"
  get 'products/index_moderator', to: 'products#index_moderator', as: 'index_moderator'

  resources :products
  resources :chats
  resources :orders
  resources :reviews
  resources :messages
  resources :users

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def review_params
		params.require(:review).permit(:id_user, :id_product, :content, :grade)
	end

	def index
		if user_signed_in?
			if current_user.admin?
				@reviews = Review.all
				render "index_admin"

			else
				@reviews = Review.where(id_user: current_user.id)

			end
		else
			redirect_to "/"
		end
	end

	def create
		@review = Review.new(review_params)

		if @review.save
			render json: {message: "Review was successfully created."}
		else
			render json: @review.errors, status: :unprocessable_entity

		end
	end

	def new
		@review = Review.new
		if params[:id_order] == "-1" && params[:id_product] == "-1"
			@order = "-1"
			@product = "-1"
		else
			@order = Order.find(params[:id_order])
			@product = Product.find(params[:id_product])
		end
	end

	def update
		@user = User.find(params[:id_user])
		@review = @user.reviews.find(params[:id])

		if @review.update(review_params)
			render json: {message: "Review was successfully updated."}
		else
			render json: @review.errors, status: :unprocessable_entity
		end
	end


	def destroy
		@review = Review.find(params[:id])

		if @review.delete
			render json: {message: "Review was sucessfully deleted."}
		else
			render json: @review.errors, status: :unprocessable_entity
		end
	end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: @review) do |form| %>
  <br/>
  <%= form.hidden_field :id_user, value: current_user.id %>
  <% if @product == "-1" %>
    <%= form.hidden_field :id_product, value: -1 %>
  <% else %>
    <%= form.hidden_field :id_product, value: @product.id %>
  <% end %>
  <%= form.label :content %>
  <%= form.text_area :content %>
  <%= form.label :grade %>
  <%= form.number_field :grade, min: 0, max: 10 %>
  <br/>
  <%= form.submit class:"button" %>
<% end %>

app/views/reviews/index.html.erb
<% if user_signed_in? %>

  <p style="color: green"><%= notice %></p>

  <div id="reviews">

	<div class="content is-center has-text-centered is-size-5 mt-5">
		<h1> Nuevo Producto </h1>
	</div>

		<table class="styled-table">
			<thead>
			<tr>
				<th style="width: 25%;">Producto</th>
				<th style="width: 35%;">Opinion</th>
				<th style="width: 20%;">Calificacion</th>
				<th style="width: 20%;">Fecha</th>
			</tr>
			</thead>
			<tbody>
			<% @reviews.each do |review| %>
				<% if review.id_product == -1%>
				<tr>
					<td><%= "Pagina" %></td>
					<td><%= review.content %></td>
					<td><%= review.grade %></td>
					<td><%= review.created_at.strftime("%d/%m/%Y") %></td>
				</tr>
				<% else%>
				<% product = Product.find_by(id: review.id_product) %>
				<tr>
					<td><%= product.name %></td>
					<td><%= review.content %></td>
					<td><%= review.grade %></td>
					<td><%= review.created_at.strftime("%d/%m/%Y") %></td>
				</tr>
				<% end%>
			<% end %>
			</tbody>
		</table>
  </div>

<% else %>
  	<p> No has iniciado sesión </p>

<% end %>

app/views/reviews/index_admin.html.erb
<% if user_signed_in? %>

    <div class="content is-center has-text-centered is-size-5 mt-5">
        <h2>Reseñas</h2>
    </div>

    <p style="color: green"><%= notice %></p>

    <% if !@reviews.nil? %>

        <div class="box mx-6 my-5 is-align-self-center">
		    <div class="table-container is-flex is-justify-content-center">

                <table class="table is-fullwidth is-centered">
                    <thead>
                        <tr>
                            <th>Producto</th>
                            <th>Opinion</th>
                            <th>Calificacion</th>
                            <th>Fecha</th>
                        </tr>
                    </thead>

                    <tbody>
                        <% @reviews.each do |review| %>
                            <tr>
                                <td><%= review.content %></td>
                                <td><%= review.grade %></td>
                                <td><%= review.created_at.strftime("%d/%m/%Y") %></td>

                                <td>

                                    <div class="is-flex is-justify-content-center mt-5">
                                        <div class="buttons">
                                            <%= button_to "Cancelar Reserva", review_path(review), data: { confirm: '¿Está seguro que desea eliminar la orden?' }, method: :delete, class: "button is-small is-rounded is-danger" %>
                                        </div>
                                    </div>

                                </td>

                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>

    <% else %>
        <div class="box mx-6 my-5 is-align-self-center">
		    <div class="table-container is-flex is-justify-content-center">
                <p> No hay Reseñas </p>
            </div>
        </div>

    <% end %>

<% else %>
    <div class="box mx-6 my-5 is-align-self-center">
        <div class="table-container is-flex is-justify-content-center">
            <p> No has iniciado sesión </p>
        </div>
    </div>

<% end %>

app/views/reviews/new.html.erb
<% if user_signed_in? %>

    <div class="content is-center has-text-centered is-size-5 mt-5">
        <h1> Nueva Review </h1>
    </div>

    <%= render "form", product: @order %>

    <br>

<% else %>
    <p> No has iniciado sesión </p>

<% end %>