config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                   path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  root "products#index"
  get 'products/index_moderator', to: 'products#index_moderator', as: 'index_moderator'

  resources :products
  resources :chats
  resources :orders
  resources :reviews
  resources :messages
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  validates :id_user, presence: true
  validates :moderator_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true
  validates :id_chat, presence: true
  validates :id_user, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :id_product, presence: true
  validates :order_date, presence: true
  validates :status, presence: true
  validates :id_user, presence: true


  """
colocar validate
"""
end

app/models/product.rb
class Product < ApplicationRecord
	has_one_attached :image
  has_many :review, dependent: :destroy
  has_one :order
  has_one :user, through: :order
  validates :name, presence: true
  validates :price, presence: true
  validates :image, presence: true
  validates :id_user, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  validates :id_user, presence: true
  validates :id_product, presence: true
  validates :content, presence: true
  validates :grade, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_one_attached :images_path

  validates :name, presence: true, length: {maximum: 20}
  validates :cellphone, presence: true, length: {is: 9}, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:user, :moderator, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  has_many :order
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chat = Chat.all
  end

  def new
    @users = User.all
    @chat = Chat.new
  end

  def show
    @chat = Chat.find(params[:id])
    all_messages = Message.all
    messages_chat = Array.new
    all_messages.each do |message|
      if message.id_chat == @chat.id
        messages_chat.push(message)
      end
    end
    @messages = messages_chat
  end

  def create
    all_chats = Chat.all
    is_any = false
    all_chats.each do |chat|
      if chat.id_user == chat_params[:id_user].to_i && chat.moderator_id == chat_params[:moderator_id].to_i
        is_any = true
      end
    end
    if is_any == false
      @chat = Chat.new(chat_params)
      if @chat.save
        redirect_to @chat
      else
        render @chat.errors, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @chat = Chat.find(params[:id])
    @messages = Message.all

    @messages.each do |message|
      if message.id_chat == @chat.id
        message.destroy
      end
    end

    if @chat.destroy
      redirect_to chats_path
    else
      render json: @chat.errors, status: :unprocessable_entity
    end
  end

  def chat_params
    params.require(:chat).permit(:moderator_id, :id_user)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    content = message_params[:name] + message_params[:content]
    @message = Message.new(content: content, id_chat: message_params[:id_chat], id_user: message_params[:id_user])
    if @message.save
      redirect_to chat_path(@message.id_chat)
    else
      render @chat.errors, status: :unprocessable_entity
    end
  end

  def message_params
    params.require(:message).permit(:name, :content, :id_chat, :id_user)
  end
end


app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include Devise::Controllers::Helpers

  def order_params
    params.require(:order).permit(:id_product, :id_user, :description, :status, :order_date)
  end


  def index
    @orders = Order.all
  end


  def show
    @orders = Order.where(user_id: current_user.id)
  end


  def create
    @order = Order.new(order_params)
      @order.user_id = current_user.id # Asignar el id del usuario actual

      if @order.save
        render json: {message: "La orden ha sido recibida"}
      else
        render json: @order.errors, status: :unprocessable_entity
      end
  end
  """
update prox sprint
"""
  def update
    @order = Order.find(params[:id])

      if @order.update(order_params)
        render json: {message: "El estado de la orden se actualizo"}
      else
        render json: @order.errors, status: :unprocessable_entity
      end
  end


  def destroy
    @order = Order.find(params[:id])

      if @order.destroy
        render json: {message: "La orden se eliminó correctamente."}
      else
        render json: @order.errors, status: :unprocessable_entity
      end
  end

end


app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def review_params
		params.require(:review).permit(:id_user, :id_product, :content, :grade)
	end

	def index
		if user_signed_in?
			if current_user.admin?
				@reviews = Review.all
				render "index_admin"

			else
				@reviews = Review.where(id_user: current_user.id)

			end
		else
			redirect_to "/"
		end
	end

	def create
		@review = Review.new(review_params)

		if @review.save
			render json: {message: "Review was successfully created."}
		else
			render json: @review.errors, status: :unprocessable_entity

		end
	end

	def new
		@review = Review.new
		if params[:id_order] == "-1" && params[:id_product] == "-1"
			@order = "-1"
			@product = "-1"
		else
			@order = Order.find(params[:id_order])
			@product = Product.find(params[:id_product])
		end
	end

	def update
		@user = User.find(params[:id_user])
		@review = @user.reviews.find(params[:id])

		if @review.update(review_params)
			render json: {message: "Review was successfully updated."}
		else
			render json: @review.errors, status: :unprocessable_entity
		end
	end


	def destroy
		@review = Review.find(params[:id])

		if @review.delete
			render json: {message: "Review was sucessfully deleted."}
		else
			render json: @review.errors, status: :unprocessable_entity
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])

    if current_user.admin?

      @chats = Chat.all

      @chats.each do |chat|
        if chat.id_user == @user.id
          chat.destroy
        end
      end

      if current_user.id == @user.id
        @user.destroy
        redirect_to "/"

      else
        @user.destroy
        redirect_to users_path, notice: "Usuario eliminado correctamente"

      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_nav_admin.html.erb
<%= link_to "Ver Reseñas", reviews_path, class: "navbar-item" %>

<%= link_to "Ver Usuarios", users_path, class: "navbar-item" %>

<%= link_to "Ver Ordenes", orders_path, class: "navbar-item" %>

<%= link_to "Productos", { controller: "products", action: "index_moderator" }, class: "navbar-item" %>

<%= link_to "Chat", chats_path, class: "navbar-item" %>

app/views/layouts/_nav_user.html.erb
<%= link_to "Mis Reservas", order_path(current_user.id), class: "navbar-item" %>

<%= link_to "Mis Reseñas", reviews_path, class: "navbar-item" %>

<%= link_to "Productos", products_path, class: "navbar-item" %>

<%= link_to "Chats", chats_path, class: "navbar-item" %>

<%= link_to 'Danos tu opinion', new_review_path(id_product: -1, id_order: -1), class: "navbar-item" %>

app/views/layouts/_nav_user_not_signed.html.erb
<nav>
    <div class="navbar-end">
        <div class="navbar-item">
            <% unless session[:hide_buttons] %>
                <div class="buttons">

                    <%= link_to new_user_registration_path, class: "button is-primary" do %>
                        <strong>Registrarse</strong>
                    <% end %>

                    <%= link_to "Inicar Sesión", new_user_session_path, class: "button is-light" %>

                </div>
            <% end %>
        </div>
    </div>
</nav>

app/views/layouts/_nav_user_signed.html.erb
<nav>
    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">


            <% if current_user.images_path.attached? %>

                <div class="navbar-brand">
                    <figure class="navbar-item image is-rounded">
                        <%= image_tag current_user.images_path, class:"is-rounded is-64x64 has-background-white" %>
                    </figure>
                </div>

            <% else %>

                <div class="navbar-brand">
                    <figure class="navbar-item image is-rounded">
                        <img class="is-rounded is-64x64 has-background-white" src="https://ceslava.s3-accelerate.amazonaws.com/2016/04/mistery-man-gravatar-wordpress-avatar-persona-misteriosa-510x510.png">
                    </figure>
                </div>

            <% end %>

                <%= link_to current_user.name, edit_user_registration_path, class: "navbar-item" %>

            <% if current_user.admin? || current_user.moderator? %>
                <%= render "layouts/nav_admin" %>

            <% elsif current_user.user? %>
                <%= render "layouts/nav_user"%>

            <% end %>

            </div>

        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    <%= button_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "button is-primary"%>

                </div>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<%= render "templates/header"%>

  <body class="m-4">

    <% if user_signed_in? %>
      <%= render "layouts/nav_user_signed"%>

    <% else %>
      <%= render "layouts/nav_user_not_signed"%>

    <% end %>

    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>

    <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>

    <% session[:hide_buttons] = false %>

    <%= yield %>

  </body>

</html>

app/views/templates/_header.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Proyecto Software</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>

  </head>